import type { PeptipediaLocale } from './types'

// Existing Peptipedia copy, kept synchronous for public rendering.
const labels: Record<PeptipediaLocale, Record<string, string>> = {
  "de": {
    "plib_cat_heilung": "Heilung & Regeneration",
    "plib_cat_s_heilung": "Heilung",
    "plib_cat_wachstumshormon": "Wachstumshormon",
    "plib_cat_nootropikum": "Nootropikum",
    "plib_cat_stoffwechsel": "Stoffwechsel",
    "plib_cat_anti_aging": "Anti-Aging",
    "plib_cat_sexualgesundheit": "Sexualgesundheit",
    "plib_status_preclinical": "Präklinisch",
    "plib_status_phase_1": "Phase 1",
    "plib_status_phase_2": "Phase 2",
    "plib_status_approved": "Zugelassen",
    "plib_status_human_research": "Humanforschung",
    "plib_status_historical_approval": "Historische Zulassung",
    "plib_ev_none": "Keine",
    "plib_ev_limited": "Begrenzt",
    "plib_ev_sparse": "Gering",
    "plib_ev_moderate": "Moderat",
    "plib_ev_strong": "Stark",
    "plib_ev_extensive": "Umfangreich",
    "plib_conf_high": "Hohe Konfidenz",
    "plib_conf_moderate": "Moderate Konfidenz",
    "plib_conf_low": "Niedrige Konfidenz",
    "plib_conf_very_limited": "Sehr begrenzte Evidenz",
    "plib_sort_default": "Standard",
    "plib_sort_evidence_desc": "Evidenz ↓",
    "plib_sort_evidence_asc": "Evidenz ↑",
    "plib_sort_name_asc": "Name A–Z",
    "plib_sort_name_desc": "Name Z–A",
    "plib_all": "Alle",
    "plib_hero_kicker": "Forschungsdatenbank",
    "plib_hero_sub": "Evidenzbasierte Forschungsprofile. Kein medizinischer Rat.",
    "plib_search_placeholder": "Peptid oder Tag suchen…",
    "plib_sort_label": "Sortieren",
    "plib_category_label": "Kategorie",
    "plib_status_label": "Forschungsstatus",
    "plib_human_evidence_label": "Humanstudien",
    "plib_human_yes": "Vorhanden",
    "plib_human_strong": "Moderat / Stark",
    "plib_tags_label": "Tags",
    "plib_reset_filters": "Alle Filter zurücksetzen",
    "plib_reset_filters_short": "Filter zurücksetzen",
    "plib_count_one": "{{count}} Peptid",
    "plib_count_other": "{{count}} Peptide",
    "plib_filtered": "gefiltert",
    "plib_empty": "Keine Peptide für diese Auswahl.",
    "plib_load_error": "Ladefehler",
    "plib_disclaimer_list": "Alle Angaben basieren auf veröffentlichten Forschungsstudien. Keine Therapieempfehlung.",
    "plib_ev_human_short": "Human",
    "plib_ev_animal_short": "Tier",
    "plib_ev_clinical_short": "Klinisch",
    "plib_profile": "Profil",
    "plib_not_found": "Peptid nicht gefunden.",
    "plib_back_to_library": "Zurück zur Bibliothek",
    "plib_breadcrumb_library": "Bibliothek",
    "plib_detail_disclaimer": "Forschungsdaten. Keine Therapieempfehlung. Dosierungen stammen aus publizierten Studienprotokollen — nicht aus klinischen Leitlinien.",
    "plib_mechanism": "Wirkmechanismus",
    "plib_research_areas": "Forschungsbereiche",
    "plib_evidence": "Evidenzlage",
    "plib_ev_human_long": "Humane Daten",
    "plib_ev_animal_long": "Tierstudien",
    "plib_ev_clinical_long": "Klinische Daten",
    "plib_total_score": "Gesamtscore",
    "plib_study_dosages": "Dosierungen aus publizierten Studien",
    "plib_dosage_note": "Nicht „empfohlene Dosierung“ — Angaben aus Studienprotokollen",
    "plib_administration": "Verabreichungswege (in Studien)",
    "plib_half_life": "Halbwertszeit",
    "plib_side_effects": "Berichtete Nebenwirkungen",
    "plib_contraindications": "Kontraindikationen & Hinweise",
    "plib_research_gaps": "Wissenslücken & Limitierungen",
    "plib_full_mechanism": "Vollständiger Wirkmechanismus",
    "plib_pubmed_cta": "Studien auf PubMed suchen",
    "plib_bottom_disclaimer": "Kein medizinischer Rat · Nur Forschungsdaten · Fachperson konsultieren"
  },
  "en": {
    "plib_cat_heilung": "Healing & Regeneration",
    "plib_cat_s_heilung": "Healing",
    "plib_cat_wachstumshormon": "Growth Hormone",
    "plib_cat_nootropikum": "Nootropic",
    "plib_cat_stoffwechsel": "Metabolism",
    "plib_cat_anti_aging": "Anti-Aging",
    "plib_cat_sexualgesundheit": "Sexual Health",
    "plib_status_preclinical": "Preclinical",
    "plib_status_phase_1": "Phase 1",
    "plib_status_phase_2": "Phase 2",
    "plib_status_approved": "Approved",
    "plib_status_human_research": "Human research",
    "plib_status_historical_approval": "Historical approval",
    "plib_ev_none": "None",
    "plib_ev_limited": "Limited",
    "plib_ev_sparse": "Sparse",
    "plib_ev_moderate": "Moderate",
    "plib_ev_strong": "Strong",
    "plib_ev_extensive": "Extensive",
    "plib_conf_high": "High confidence",
    "plib_conf_moderate": "Moderate confidence",
    "plib_conf_low": "Low confidence",
    "plib_conf_very_limited": "Very limited evidence",
    "plib_sort_default": "Default",
    "plib_sort_evidence_desc": "Evidence ↓",
    "plib_sort_evidence_asc": "Evidence ↑",
    "plib_sort_name_asc": "Name A–Z",
    "plib_sort_name_desc": "Name Z–A",
    "plib_all": "All",
    "plib_hero_kicker": "Research Database",
    "plib_hero_sub": "Evidence-based research profiles. Not medical advice.",
    "plib_search_placeholder": "Search peptide or tag…",
    "plib_sort_label": "Sort",
    "plib_category_label": "Category",
    "plib_status_label": "Research status",
    "plib_human_evidence_label": "Human studies",
    "plib_human_yes": "Available",
    "plib_human_strong": "Moderate / Strong",
    "plib_tags_label": "Tags",
    "plib_reset_filters": "Reset all filters",
    "plib_reset_filters_short": "Reset filters",
    "plib_count_one": "{{count}} peptide",
    "plib_count_other": "{{count}} peptides",
    "plib_filtered": "filtered",
    "plib_empty": "No peptides match this selection.",
    "plib_load_error": "Loading error",
    "plib_disclaimer_list": "All information is based on published research studies. Not a treatment recommendation.",
    "plib_ev_human_short": "Human",
    "plib_ev_animal_short": "Animal",
    "plib_ev_clinical_short": "Clinical",
    "plib_profile": "Profile",
    "plib_not_found": "Peptide not found.",
    "plib_back_to_library": "Back to library",
    "plib_breadcrumb_library": "Library",
    "plib_detail_disclaimer": "Research data. Not a treatment recommendation. Dosages come from published study protocols — not from clinical guidelines.",
    "plib_mechanism": "Mechanism of action",
    "plib_research_areas": "Research areas",
    "plib_evidence": "Evidence",
    "plib_ev_human_long": "Human data",
    "plib_ev_animal_long": "Animal studies",
    "plib_ev_clinical_long": "Clinical data",
    "plib_total_score": "Overall score",
    "plib_study_dosages": "Dosages from published studies",
    "plib_dosage_note": "Not a \"recommended dosage\" — data from study protocols",
    "plib_administration": "Routes of administration (in studies)",
    "plib_half_life": "Half-life",
    "plib_side_effects": "Reported side effects",
    "plib_contraindications": "Contraindications & notes",
    "plib_research_gaps": "Knowledge gaps & limitations",
    "plib_full_mechanism": "Full mechanism of action",
    "plib_pubmed_cta": "Search studies on PubMed",
    "plib_bottom_disclaimer": "Not medical advice · Research data only · Consult a professional"
  }
}

export function peptipediaText(locale: PeptipediaLocale) {
  return (key: string, options?: { count: number }): string => {
    const resolvedKey = options ? `${key}_${options.count === 1 ? 'one' : 'other'}` : key
    return (labels[locale][resolvedKey] ?? key).replace('{{count}}', String(options?.count ?? ''))
  }
}
