-- GENERIERT von scripts/generate-substance-catalog-sql.mjs.
-- Nicht von Hand aendern — die Quelle ist scripts/substance-catalog-source.mjs.
-- Neu erzeugen mit: npm run catalog:sql
--
-- 335 Substanzen, davon 24 Kombipraeparate.
-- Der Upsert trifft den Unique-Index auf lower(canonical_name): bekannte
-- Zeilen werden aktualisiert, neue angelegt. Ein zweiter Lauf aendert nichts.
--
-- SETZT supabase-my-stack-catalog-combinations.sql VORAUS — dort entsteht
-- die Spalte component_names, die diese Datei fuellt.

begin;

-- 2 Umbenennung(en): bestehende Zeilen behalten ihre id.
update public.substance_catalog set canonical_name = 'Retatrutid', updated_at = now()
where lower(canonical_name) = lower('Retatrutide')
  and not exists (
    select 1 from public.substance_catalog andere
    where lower(andere.canonical_name) = lower('Retatrutid')
  );

update public.substance_catalog set canonical_name = 'Melanotan II', updated_at = now()
where lower(canonical_name) = lower('Melanotan II (MT2)')
  and not exists (
    select 1 from public.substance_catalog andere
    where lower(andere.canonical_name) = lower('Melanotan II')
  );

with quelle (canonical_name, aliases, default_category, suggested_dosage_forms, suggested_units, pk_profile_name, component_names) as (
  values
    ('Semaglutid', array['Semaglutide', 'Ozempic', 'Wegovy', 'Rybelsus']::text[], 'peptide', array['pen', 'vial', 'tablet']::text[], array['mg', 'mcg']::text[], 'Semaglutide', '{}'::text[]),
    ('Tirzepatid', array['Tirzepatide', 'Mounjaro', 'Zepbound']::text[], 'peptide', array['pen', 'vial']::text[], array['mg', 'mcg']::text[], 'Tirzepatide', '{}'::text[]),
    ('Liraglutid', array['Liraglutide', 'Victoza', 'Saxenda']::text[], 'peptide', array['pen']::text[], array['mg']::text[], 'Liraglutide', '{}'::text[]),
    ('Exenatid', array['Exenatide', 'Byetta', 'Bydureon']::text[], 'peptide', array['pen', 'vial']::text[], array['mcg', 'mg']::text[], 'Exenatide', '{}'::text[]),
    ('Retatrutid', array['Retatrutide', 'LY3437943', 'Reta', 'Triple-G']::text[], 'peptide', array['vial', 'pen']::text[], array['mg', 'mcg']::text[], 'Retatrutide', '{}'::text[]),
    ('Cagrilintid', array['Cagrilintide', 'AM833', 'NN9838', 'Cagri']::text[], 'peptide', array['vial', 'pen']::text[], array['mg', 'mcg']::text[], 'Cagrilintide', '{}'::text[]),
    ('Survodutid', array['Survodutide', 'BI 456906']::text[], 'peptide', array['vial', 'pen']::text[], array['mg', 'mcg']::text[], 'Survodutide', '{}'::text[]),
    ('Mazdutid', array['Mazdutide', 'IBI362', 'LY3305677']::text[], 'peptide', array['vial', 'pen']::text[], array['mg', 'mcg']::text[], 'Mazdutide', '{}'::text[]),
    ('Orforglipron', array['LY3502970']::text[], 'peptide', array['tablet', 'capsule']::text[], array['mg']::text[], 'Orforglipron', '{}'::text[]),
    ('BPC-157', array['Body Protection Compound', 'Body Protection Compound 157', 'PL-14736']::text[], 'peptide', array['vial', 'capsule', 'nasal_spray', 'tube']::text[], array['mg', 'mcg']::text[], 'BPC-157', '{}'::text[]),
    ('TB-500', array['Thymosin Beta-4', 'TB4']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'TB-500', '{}'::text[]),
    ('GHK-Cu', array['Copper Peptide', 'Kupferpeptid']::text[], 'peptide', array['vial', 'gel', 'tube']::text[], array['mg']::text[], 'GHK-Cu', '{}'::text[]),
    ('KPV', array['Lysin-Prolin-Valin']::text[], 'peptide', array['vial', 'capsule']::text[], array['mg', 'mcg']::text[], 'KPV', '{}'::text[]),
    ('CJC-1295', array['CJC-1295 DAC', 'CJC-1295 with DAC']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'CJC-1295 DAC', '{}'::text[]),
    ('CJC-1295 ohne DAC', array['CJC-1295 no DAC', 'Modified GRF 1-29', 'Mod GRF 1-29']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'CJC-1295 no DAC', '{}'::text[]),
    ('Ipamorelin', '{}'::text[], 'peptide', array['vial', 'nasal_spray']::text[], array['mcg', 'mg']::text[], 'Ipamorelin', '{}'::text[]),
    ('GHRP-2', array['Pralmorelin']::text[], 'peptide', array['vial', 'nasal_spray']::text[], array['mcg', 'mg']::text[], 'GHRP-2', '{}'::text[]),
    ('GHRP-6', '{}'::text[], 'peptide', array['vial', 'nasal_spray']::text[], array['mcg', 'mg']::text[], 'GHRP-6', '{}'::text[]),
    ('Hexarelin', array['Examorelin']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'Hexarelin', '{}'::text[]),
    ('Sermorelin', '{}'::text[], 'peptide', array['vial', 'ampoule']::text[], array['mcg', 'mg']::text[], 'Sermorelin', '{}'::text[]),
    ('Tesamorelin', array['Egrifta']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'Tesamorelin', '{}'::text[]),
    ('MK-677', array['Ibutamoren', 'Nutrobal']::text[], 'peptide', array['capsule', 'tablet', 'drops']::text[], array['mg']::text[], 'MK-677', '{}'::text[]),
    ('MOTS-c', array['Mitochondrial ORF 12S rRNA-c']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'MOTS-c', '{}'::text[]),
    ('AOD-9604', array['AOD9604', 'hGH 176-191 (Tyr)']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'AOD-9604', '{}'::text[]),
    ('HGH Fragment 176-191', array['HGH Frag', 'Frag 176-191', 'Fragment 176-191']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'HGH Fragment 176-191', '{}'::text[]),
    ('Thymosin Alpha-1', array['Thymalfasin', 'Zadaxin', 'Ta1']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'Thymosin Alpha-1', '{}'::text[]),
    ('DSIP', array['Delta Sleep-Inducing Peptide', 'Delta-Schlaf-induzierendes Peptid']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'DSIP', '{}'::text[]),
    ('Kisspeptin-10', array['KP-10', 'Metastin 45-54']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], 'Kisspeptin-10', '{}'::text[]),
    ('Semax', '{}'::text[], 'peptide', array['nasal_spray', 'vial', 'drops']::text[], array['mg', 'mcg']::text[], 'Semax', '{}'::text[]),
    ('Selank', '{}'::text[], 'peptide', array['nasal_spray', 'vial', 'drops']::text[], array['mg', 'mcg']::text[], 'Selank', '{}'::text[]),
    ('Dihexa', '{}'::text[], 'peptide', array['capsule', 'vial']::text[], array['mg', 'mcg']::text[], 'Dihexa', '{}'::text[]),
    ('Cerebrolysin', '{}'::text[], 'peptide', array['ampoule', 'vial']::text[], array['ml', 'mg']::text[], 'Cerebrolysin', '{}'::text[]),
    ('NA-Semax Amidat', array['NA-Semax Amidate', 'N-Acetyl Semax Amidate', 'NA-Semax']::text[], 'peptide', array['nasal_spray', 'drops', 'vial']::text[], array['mg', 'mcg']::text[], 'NA-Semax Amidate', '{}'::text[]),
    ('PT-141', array['Bremelanotid', 'Bremelanotide', 'Vyleesi']::text[], 'peptide', array['vial', 'nasal_spray']::text[], array['mg', 'mcg']::text[], 'PT-141', '{}'::text[]),
    ('Melanotan II', array['Melanotan 2', 'MT-2', 'MT-II']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'Melanotan II', '{}'::text[]),
    ('Epithalon', array['Epitalon', 'Epithalone']::text[], 'peptide', array['vial', 'capsule', 'tablet']::text[], array['mg', 'mcg']::text[], 'Epithalon', '{}'::text[]),
    ('SS-31', array['Elamipretid', 'Elamipretide', 'MTP-131']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'SS-31', '{}'::text[]),
    ('Humanin', '{}'::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], 'Humanin', '{}'::text[]),
    ('Testosteron', array['Testosterone']::text[], 'hormone', array['vial', 'ampoule', 'gel', 'patch', 'capsule', 'pen']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Testosteron Enantat', array['Testosterone Enanthate', 'Test E']::text[], 'hormone', array['vial', 'ampoule', 'pen']::text[], array['mg']::text[], 'Testosterone Enanthate', '{}'::text[]),
    ('Testosteron Cypionat', array['Testosterone Cypionate', 'Test C']::text[], 'hormone', array['vial', 'ampoule']::text[], array['mg']::text[], 'Testosterone Cypionate', '{}'::text[]),
    ('Testosteron Propionat', array['Testosterone Propionate', 'Test P']::text[], 'hormone', array['vial', 'ampoule']::text[], array['mg']::text[], 'Testosterone Propionate', '{}'::text[]),
    ('HCG', array['Human Chorionic Gonadotropin', 'Humanes Choriongonadotropin', 'Choriongonadotropin']::text[], 'hormone', array['vial', 'ampoule']::text[], array['IU', 'mg']::text[], 'HCG', '{}'::text[]),
    ('IGF-1 LR3', array['Long R3 IGF-1', 'LR3']::text[], 'hormone', array['vial']::text[], array['mcg', 'mg']::text[], 'IGF-1 LR3', '{}'::text[]),
    ('HGH', array['Somatropin', 'Human Growth Hormone', 'Wachstumshormon']::text[], 'hormone', array['vial', 'pen']::text[], array['IU', 'mg']::text[], 'HGH', '{}'::text[]),
    ('Vitamin D3', array['Cholecalciferol', 'Colecalciferol']::text[], 'vitamin', array['capsule', 'drops', 'tablet', 'spray']::text[], array['IU', 'mcg']::text[], null, '{}'::text[]),
    ('Vitamin K2', array['Menachinon-7', 'MK-7', 'Menaquinon']::text[], 'vitamin', array['capsule', 'drops', 'tablet']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Magnesium', array['Magnesiumcitrat', 'Magnesium citrate', 'Magnesiumöl']::text[], 'supplement', array['capsule', 'tablet', 'powder', 'spray', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Omega-3', array['Omega 3', 'Fischöl', 'Fish oil', 'EPA/DHA']::text[], 'supplement', array['capsule', 'drops']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Creatin', array['Kreatin', 'Creatine', 'Creatin-Monohydrat']::text[], 'supplement', array['powder', 'capsule', 'tablet']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('Metformin', array['Metformin HCl', 'Glucophage']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Metformin', '{}'::text[]),
    ('Melatonin', '{}'::text[], 'supplement', array['tablet', 'capsule', 'drops', 'spray']::text[], array['mg', 'mcg']::text[], 'Melatonin', '{}'::text[]),
    ('Vitamin C', array['Ascorbinsäure', 'Ascorbic acid']::text[], 'vitamin', array['capsule', 'tablet', 'powder']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Vitamin A', array['Retinol', 'Retinylpalmitat']::text[], 'vitamin', array['capsule', 'drops']::text[], array['IU', 'mcg']::text[], null, '{}'::text[]),
    ('Vitamin E', array['Tocopherol', 'Alpha-Tocopherol']::text[], 'vitamin', array['capsule', 'drops']::text[], array['IU', 'mg']::text[], null, '{}'::text[]),
    ('Vitamin B1', array['Thiamin', 'Benfotiamin']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vitamin B2', array['Riboflavin']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vitamin B3', array['Niacin', 'Nicotinamid', 'Nicotinsäure']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vitamin B5', array['Pantothensäure', 'Calcium-Pantothenat']::text[], 'vitamin', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vitamin B6', array['Pyridoxin', 'P5P', 'Pyridoxal-5-Phosphat']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vitamin B7', array['Biotin', 'Vitamin H']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Folsäure', array['Vitamin B9', 'Folat', 'Methylfolat', '5-MTHF']::text[], 'vitamin', array['tablet', 'capsule']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Vitamin B12', array['Cobalamin', 'Methylcobalamin', 'Hydroxocobalamin', 'Cyanocobalamin']::text[], 'vitamin', array['tablet', 'capsule', 'drops', 'spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Vitamin B-Komplex', array['B-Komplex', 'Vitamin B Complex']::text[], 'vitamin', array['capsule', 'tablet']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Zink', array['Zinc', 'Zinkgluconat', 'Zinkbisglycinat', 'Zinkpicolinat']::text[], 'supplement', array['tablet', 'capsule', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Eisen', array['Ferrum', 'Iron', 'Eisenbisglycinat', 'Eisensulfat']::text[], 'supplement', array['tablet', 'capsule', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Calcium', array['Kalzium', 'Calciumcitrat', 'Calciumcarbonat']::text[], 'supplement', array['tablet', 'capsule', 'powder']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Kalium', array['Potassium', 'Kaliumcitrat']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Selen', array['Selenium', 'Natriumselenit', 'Selenomethionin']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Jod', array['Iod', 'Iodine', 'Kaliumiodid']::text[], 'supplement', array['tablet', 'capsule', 'drops']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Kupfer', array['Copper', 'Kupferbisglycinat']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Mangan', array['Manganese']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Chrom', array['Chromium', 'Chrompicolinat']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Molybdän', array['Molybdenum']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Koffein', array['Caffeine', 'Coffein']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mg']::text[], 'Koffein', '{}'::text[]),
    ('L-Theanin', array['Theanin', 'L-Theanine']::text[], 'supplement', array['capsule', 'tablet', 'powder']::text[], array['mg']::text[], 'L-Theanin', '{}'::text[]),
    ('L-Citrullin', array['Citrullin', 'Citrullin-Malat', 'L-Citrulline']::text[], 'supplement', array['powder', 'capsule']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('L-Arginin', array['Arginin', 'L-Arginine', 'AAKG']::text[], 'supplement', array['capsule', 'powder', 'tablet']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Beta-Alanin', array['Beta Alanine', 'β-Alanin']::text[], 'supplement', array['powder', 'capsule']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('Taurin', array['Taurine']::text[], 'supplement', array['powder', 'capsule']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('L-Carnitin', array['Carnitin', 'Acetyl-L-Carnitin', 'ALCAR']::text[], 'supplement', array['capsule', 'tablet', 'powder']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Glycin', array['Glycine']::text[], 'supplement', array['powder', 'capsule']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('NAC', array['N-Acetyl-Cystein', 'N-Acetylcystein', 'Acetylcystein']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], 'NAC', '{}'::text[]),
    ('Whey Protein', array['Molkenprotein', 'Whey', 'Proteinpulver']::text[], 'supplement', array['powder']::text[], array['g']::text[], null, '{}'::text[]),
    ('Kollagen', array['Collagen', 'Kollagenpeptide', 'Collagen peptides']::text[], 'supplement', array['powder', 'capsule']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('Inositol', array['Myo-Inositol']::text[], 'supplement', array['powder', 'capsule']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('Ashwagandha', array['Withania somnifera', 'KSM-66', 'Schlafbeere']::text[], 'supplement', array['capsule', 'tablet', 'powder']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Kurkuma', array['Curcumin', 'Turmeric', 'Kurkumaextrakt']::text[], 'supplement', array['capsule', 'tablet', 'powder']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Rhodiola rosea', array['Rosenwurz', 'Rhodiola']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ginkgo biloba', array['Ginkgo']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Mariendistel', array['Silymarin', 'Silybum marianum']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Baldrian', array['Valeriana', 'Valerian']::text[], 'supplement', array['tablet', 'capsule', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('5-HTP', array['5-Hydroxytryptophan', 'Griffonia']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], '5-HTP', '{}'::text[]),
    ('Coenzym Q10', array['CoQ10', 'Ubiquinol', 'Ubichinon']::text[], 'supplement', array['capsule']::text[], array['mg']::text[], 'Coenzym Q10', '{}'::text[]),
    ('Alpha-Liponsäure', array['ALA', 'Alpha Lipoic Acid', 'Liponsäure']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Resveratrol', array['Trans-Resveratrol']::text[], 'supplement', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Berberin', array['Berberine', 'Berberin-HCl']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Spermidin', array['Spermidine']::text[], 'supplement', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('NMN', array['Nicotinamid-Mononukleotid', 'Nicotinamide Mononucleotide']::text[], 'supplement', array['capsule', 'powder']::text[], array['mg']::text[], null, '{}'::text[]),
    ('NR', array['Nicotinamid-Ribosid', 'Nicotinamide Riboside', 'Niagen']::text[], 'supplement', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ibuprofen', array['Nurofen']::text[], 'medication', array['tablet', 'capsule', 'gel', 'tube']::text[], array['mg']::text[], 'Ibuprofen', '{}'::text[]),
    ('Paracetamol', array['Acetaminophen', 'Ben-u-ron']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Paracetamol', '{}'::text[]),
    ('Acetylsalicylsäure', array['ASS', 'Aspirin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Acetylsalicylsäure', '{}'::text[]),
    ('Pantoprazol', array['Pantoprazole', 'Pantozol']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Pantoprazol', '{}'::text[]),
    ('Omeprazol', array['Omeprazole']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], 'Omeprazol', '{}'::text[]),
    ('Atorvastatin', array['Sortis']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Atorvastatin', '{}'::text[]),
    ('Rosuvastatin', array['Crestor']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Rosuvastatin', '{}'::text[]),
    ('Simvastatin', array['Zocor']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Simvastatin', '{}'::text[]),
    ('Ramipril', array['Delix']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Ramipril', '{}'::text[]),
    ('Bisoprolol', array['Concor']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Bisoprolol', '{}'::text[]),
    ('Metoprolol', array['Beloc']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Metoprolol', '{}'::text[]),
    ('Amlodipin', array['Amlodipine', 'Norvasc']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Amlodipin', '{}'::text[]),
    ('Candesartan', array['Blopress']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Candesartan', '{}'::text[]),
    ('Sertralin', array['Sertraline', 'Zoloft']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Sertralin', '{}'::text[]),
    ('Escitalopram', array['Cipralex']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Escitalopram', '{}'::text[]),
    ('Venlafaxin', array['Venlafaxine', 'Trevilor']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], 'Venlafaxin', '{}'::text[]),
    ('Bupropion', array['Elontril', 'Wellbutrin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Bupropion', '{}'::text[]),
    ('Methylphenidat', array['Methylphenidate', 'Ritalin', 'Medikinet', 'Concerta']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Methylphenidat', '{}'::text[]),
    ('Lisdexamfetamin', array['Lisdexamfetamine', 'Elvanse', 'Vyvanse']::text[], 'medication', array['capsule']::text[], array['mg']::text[], 'Lisdexamfetamin', '{}'::text[]),
    ('Modafinil', array['Vigil', 'Provigil']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Modafinil', '{}'::text[]),
    ('Finasterid', array['Finasteride', 'Propecia']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Finasterid', '{}'::text[]),
    ('Dutasterid', array['Dutasteride', 'Avodart']::text[], 'medication', array['capsule']::text[], array['mg']::text[], 'Dutasterid', '{}'::text[]),
    ('Tadalafil', array['Cialis']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Tadalafil', '{}'::text[]),
    ('Sildenafil', array['Viagra']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Sildenafil', '{}'::text[]),
    ('Anastrozol', array['Anastrozole', 'Arimidex']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Anastrozol', '{}'::text[]),
    ('Tamoxifen', array['Nolvadex']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Tamoxifen', '{}'::text[]),
    ('Enclomifen', array['Enclomiphene', 'Enclomifencitrat']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], 'Enclomifen', '{}'::text[]),
    ('Levothyroxin', array['Levothyroxine', 'L-Thyroxin', 'Euthyrox', 'T4']::text[], 'medication', array['tablet']::text[], array['mcg']::text[], 'Levothyroxin', '{}'::text[]),
    ('Liothyronin', array['Liothyronine', 'T3', 'Thybon']::text[], 'medication', array['tablet']::text[], array['mcg']::text[], 'Liothyronin', '{}'::text[]),
    ('Allopurinol', array['Zyloric']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Allopurinol', '{}'::text[]),
    ('Cetirizin', array['Cetirizine', 'Zyrtec']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Cetirizin', '{}'::text[]),
    ('Loratadin', array['Loratadine', 'Lorano']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Loratadin', '{}'::text[]),
    ('Prednisolon', array['Prednisolone', 'Decortin H']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Prednisolon', '{}'::text[]),
    ('Amoxicillin', array['Amoxi']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], 'Amoxicillin', '{}'::text[]),
    ('Dapagliflozin', array['Forxiga', 'Farxiga']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Dapagliflozin', '{}'::text[]),
    ('Empagliflozin', array['Jardiance']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Empagliflozin', '{}'::text[]),
    ('Naltrexon', array['Naltrexone', 'LDN', 'Low Dose Naltrexone']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], 'Naltrexon', '{}'::text[]),
    ('Rapamycin', array['Sirolimus', 'Rapamune']::text[], 'medication', array['tablet']::text[], array['mg']::text[], 'Rapamycin', '{}'::text[]),
    ('DHEA', array['Dehydroepiandrosteron', 'Prasteron']::text[], 'hormone', array['capsule', 'tablet']::text[], array['mg']::text[], 'DHEA', '{}'::text[]),
    ('Pregnenolon', array['Pregnenolone']::text[], 'hormone', array['capsule', 'tablet']::text[], array['mg']::text[], 'Pregnenolon', '{}'::text[]),
    ('Östradiol', array['Estradiol', 'Oestradiol', 'Estrogel']::text[], 'hormone', array['tablet', 'gel', 'patch']::text[], array['mg', 'mcg']::text[], 'Östradiol', '{}'::text[]),
    ('Progesteron', array['Progesterone', 'Utrogest']::text[], 'hormone', array['capsule', 'tablet', 'gel', 'tube']::text[], array['mg']::text[], 'Progesteron', '{}'::text[]),
    ('Diclofenac', array['Voltaren', 'Diclo']::text[], 'medication', array['gel', 'tube', 'tablet', 'patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ketoprofen', array['Gabrilen']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Heparin', array['Heparin-Salbe', 'Heparinoid']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lidocain', array['Lidocaine', 'Xylocain']::text[], 'medication', array['gel', 'tube', 'spray', 'patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Capsaicin', array['Cayennepfeffer-Extrakt']::text[], 'medication', array['gel', 'tube', 'patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Hydrocortison', array['Hydrocortisone']::text[], 'medication', array['gel', 'tube', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Mometason', array['Mometasone', 'Nasonex']::text[], 'medication', array['gel', 'tube', 'nasal_spray']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Betamethason', array['Betamethasone']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Tretinoin', array['Vitamin-A-Säure', 'Retinsäure']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Adapalen', array['Adapalene', 'Differin']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Benzoylperoxid', array['BPO', 'Benzoyl peroxide']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Azelainsäure', array['Azelaic acid', 'Skinoren']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Clotrimazol', array['Clotrimazole', 'Canesten']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Tacrolimus', array['Protopic']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Minoxidil', array['Regaine', 'Rogaine']::text[], 'medication', array['spray', 'drops', 'gel', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Dexpanthenol', array['Bepanthen', 'Panthenol']::text[], 'medication', array['gel', 'tube', 'drops', 'nasal_spray']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Zinkoxid', array['Zinksalbe', 'Zinc oxide']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Arnika', array['Arnica montana', 'Bergwohlverleih']::text[], 'supplement', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Beinwell', array['Symphytum', 'Wallwurz']::text[], 'supplement', array['gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Aloe Vera', array['Aloe']::text[], 'supplement', array['gel', 'tube', 'drops']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Kamille', array['Matricaria', 'Chamomilla']::text[], 'supplement', array['drops', 'gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Nikotin', array['Nicotine', 'Nicorette', 'Nikotinersatz']::text[], 'medication', array['patch', 'spray']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fentanyl', array['Durogesic']::text[], 'medication', array['patch']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Buprenorphin', array['Buprenorphine', 'Transtec', 'Norspan']::text[], 'medication', array['patch', 'tablet']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Scopolamin', array['Scopoderm', 'Hyoscin']::text[], 'medication', array['patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Rivastigmin', array['Rivastigmine', 'Exelon']::text[], 'medication', array['patch', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Rotigotin', array['Rotigotine', 'Neupro']::text[], 'medication', array['patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Xylometazolin', array['Xylometazoline', 'Otriven', 'Olynth']::text[], 'medication', array['nasal_spray']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Oxymetazolin', array['Oxymetazoline', 'Nasivin']::text[], 'medication', array['nasal_spray']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Fluticason', array['Fluticasone', 'Flutide', 'Avamys']::text[], 'medication', array['nasal_spray', 'spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Azelastin', array['Azelastine', 'Vividrin']::text[], 'medication', array['nasal_spray', 'drops']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Budesonid', array['Budesonide', 'Pulmicort']::text[], 'medication', array['spray', 'nasal_spray', 'capsule']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Salbutamol', array['Albuterol', 'Sultanol', 'Ventolin']::text[], 'medication', array['spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Glyceroltrinitrat', array['Nitroglycerin', 'Nitrolingual', 'GTN']::text[], 'medication', array['spray', 'patch']::text[], array['mg']::text[], null, '{}'::text[]),
    ('CBD', array['Cannabidiol', 'CBD-Öl']::text[], 'supplement', array['drops', 'capsule', 'spray']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Hyaluronsäure', array['Hyaluronic acid', 'Hyaluron']::text[], 'supplement', array['drops', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Propolis', array['Bienenharz']::text[], 'supplement', array['drops', 'spray', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ginseng', array['Panax ginseng', 'Roter Ginseng']::text[], 'supplement', array['capsule', 'drops', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Echinacea', array['Sonnenhut']::text[], 'supplement', array['drops', 'tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('SLU-PP-332', array['SLU PP 332', 'SLUPP-332', 'SLUPP332']::text[], 'peptide', array['vial', 'capsule']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('CJC-1295 ohne DAC + Ipamorelin', array['CJC-1295 no DAC + Ipamorelin', 'CJC + Ipamorelin', 'CJC/Ipa', 'Mod GRF 1-29 + Ipamorelin']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], null, array['CJC-1295 ohne DAC', 'Ipamorelin']::text[]),
    ('CJC-1295 DAC + Ipamorelin', array['CJC-1295 with DAC + Ipamorelin', 'CJC DAC + Ipa']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], null, array['CJC-1295', 'Ipamorelin']::text[]),
    ('BPC-157 + TB-500', array['BPC-157 und TB-500', 'BPC/TB-500', 'Wolverine Blend']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], null, array['BPC-157', 'TB-500']::text[]),
    ('GHRP-2 + CJC-1295 ohne DAC', array['GHRP-2 + Mod GRF 1-29', 'GHRP-2 / CJC no DAC']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], null, array['GHRP-2', 'CJC-1295 ohne DAC']::text[]),
    ('GHRP-6 + CJC-1295 ohne DAC', array['GHRP-6 + Mod GRF 1-29', 'GHRP-6 / CJC no DAC']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], null, array['GHRP-6', 'CJC-1295 ohne DAC']::text[]),
    ('Sermorelin + Ipamorelin', array['Sermorelin/Ipamorelin']::text[], 'peptide', array['vial']::text[], array['mcg', 'mg']::text[], null, array['Sermorelin', 'Ipamorelin']::text[]),
    ('Tesamorelin + Ipamorelin', array['Tesamorelin/Ipamorelin', 'Tesa + Ipa']::text[], 'peptide', array['vial']::text[], array['mg', 'mcg']::text[], null, array['Tesamorelin', 'Ipamorelin']::text[]),
    ('Semaglutid + Cagrilintid', array['CagriSema', 'Semaglutide + Cagrilintide']::text[], 'peptide', array['pen', 'vial']::text[], array['mg', 'mcg']::text[], null, array['Semaglutid', 'Cagrilintid']::text[]),
    ('Vitamin D3 + K2', array['Vitamin D3 K2', 'D3 + K2', 'D3K2', 'Vitamin D3 plus K2']::text[], 'vitamin', array['capsule', 'drops', 'tablet']::text[], array['IU', 'mcg', 'mg']::text[], null, array['Vitamin D3', 'Vitamin K2']::text[]),
    ('Calcium + Vitamin D3', array['Calcium D3', 'Calcium-Vitamin-D3', 'Calcium plus D3']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mg', 'IU']::text[], null, array['Calcium', 'Vitamin D3']::text[]),
    ('Eisen + Vitamin C', array['Eisen mit Vitamin C', 'Iron + Vitamin C']::text[], 'supplement', array['tablet', 'capsule']::text[], array['mg']::text[], null, array['Eisen', 'Vitamin C']::text[]),
    ('ZMA', array['Zink-Magnesium-Aspartat', 'Zink + Magnesium + B6', 'ZMA Komplex']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg', 'mcg']::text[], null, array['Zink', 'Magnesium', 'Vitamin B6']::text[]),
    ('NMN + Resveratrol', array['NMN mit Resveratrol', 'NMN/Resveratrol']::text[], 'supplement', array['capsule']::text[], array['mg']::text[], null, array['NMN', 'Resveratrol']::text[]),
    ('Koffein + L-Theanin', array['Caffeine + L-Theanine', 'Koffein/Theanin']::text[], 'supplement', array['capsule', 'tablet']::text[], array['mg']::text[], null, array['Koffein', 'L-Theanin']::text[]),
    ('Ibuprofen + Paracetamol', array['Paracetamol + Ibuprofen', 'Ibuprofen/Paracetamol']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, array['Ibuprofen', 'Paracetamol']::text[]),
    ('Metformin + Dapagliflozin', array['Xigduo', 'Dapagliflozin/Metformin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, array['Metformin', 'Dapagliflozin']::text[]),
    ('Metformin + Empagliflozin', array['Synjardy', 'Empagliflozin/Metformin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, array['Metformin', 'Empagliflozin']::text[]),
    ('Naltrexon + Bupropion', array['Mysimba', 'Contrave', 'Bupropion/Naltrexon']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, array['Naltrexon', 'Bupropion']::text[]),
    ('Levothyroxin + Liothyronin', array['Novothyral', 'Prothyrid', 'T4 + T3']::text[], 'medication', array['tablet']::text[], array['mcg']::text[], null, array['Levothyroxin', 'Liothyronin']::text[]),
    ('Ramipril + Amlodipin', array['Amlodipin/Ramipril', 'Tonarssa']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, array['Ramipril', 'Amlodipin']::text[]),
    ('Adapalen + Benzoylperoxid', array['Epiduo', 'Adapalen/BPO']::text[], 'medication', array['gel', 'tube']::text[], array['mg']::text[], null, array['Adapalen', 'Benzoylperoxid']::text[]),
    ('Fluticason + Azelastin', array['Dymista', 'Azelastin/Fluticason']::text[], 'medication', array['nasal_spray']::text[], array['mcg']::text[], null, array['Fluticason', 'Azelastin']::text[]),
    ('Xylometazolin + Dexpanthenol', array['Nasic', 'Olynth plus', 'Xylo + Dexpanthenol']::text[], 'medication', array['nasal_spray']::text[], array['mg', 'mcg']::text[], null, array['Xylometazolin', 'Dexpanthenol']::text[]),
    ('Östradiol + Progesteron', array['Estradiol + Progesteron', 'Bijuva']::text[], 'hormone', array['capsule', 'tablet', 'gel']::text[], array['mg']::text[], null, array['Östradiol', 'Progesteron']::text[]),
    ('Apixaban', array['Eliquis']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Rivaroxaban', array['Xarelto']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Edoxaban', array['Lixiana']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Dabigatran', array['Pradaxa', 'Dabigatranetexilat']::text[], 'medication', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Phenprocoumon', array['Marcumar', 'Falithrom', 'Marcuphen']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Clopidogrel', array['Plavix', 'Iscover']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ticagrelor', array['Brilique']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Enoxaparin', array['Clexane', 'Lovenox', 'Niedermolekulares Heparin']::text[], 'medication', array['pen', 'ampoule']::text[], array['mg', 'IU']::text[], null, '{}'::text[]),
    ('Hydrochlorothiazid', array['Hydrochlorothiazide', 'HCT', 'Esidrix']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Torasemid', array['Torasemide', 'Torem', 'Unat']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Furosemid', array['Furosemide', 'Lasix']::text[], 'medication', array['tablet', 'ampoule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Spironolacton', array['Spironolactone', 'Aldactone']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Eplerenon', array['Eplerenone', 'Inspra']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Valsartan', array['Diovan', 'Provas']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Losartan', array['Lorzaar', 'Cosaar']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Olmesartan', array['Votum', 'Olmetec']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Irbesartan', array['Aprovel', 'Karvea']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lisinopril', array['Acerbon', 'Lisi']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Enalapril', array['Xanef', 'Pres', 'Enahexal']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Nebivolol', array['Nebilet']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lercanidipin', array['Lercanidipine', 'Carmen', 'Corifeo']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Doxazosin', array['Cardular', 'Diblocin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Moxonidin', array['Moxonidine', 'Physiotens']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ezetimib', array['Ezetimibe', 'Ezetrol']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fenofibrat', array['Fenofibrate', 'Lipidil']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Cefuroxim', array['Cefuroxime', 'Elobact', 'Zinnat']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Doxycyclin', array['Doxycycline', 'Doxyhexal', 'Supracyclin']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Azithromycin', array['Zithromax', 'Azi']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Clarithromycin', array['Klacid', 'Mavid']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ciprofloxacin', array['Ciprobay', 'Cipro']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Levofloxacin', array['Tavanic']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Clindamycin', array['Sobelin', 'Clinda']::text[], 'medication', array['capsule', 'tablet', 'gel']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Nitrofurantoin', array['Furadantin', 'Uro-Tablinen', 'Nifurantin']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fosfomycin', array['Monuril', 'Fosfomycin-Trometamol']::text[], 'medication', array['powder']::text[], array['g', 'mg']::text[], null, '{}'::text[]),
    ('Penicillin V', array['Phenoxymethylpenicillin', 'Isocillin', 'Megacillin']::text[], 'medication', array['tablet']::text[], array['mg', 'IU']::text[], null, '{}'::text[]),
    ('Metronidazol', array['Metronidazole', 'Clont', 'Arilin']::text[], 'medication', array['tablet', 'gel']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Cotrimoxazol', array['Co-trimoxazol', 'Cotrim', 'Bactrim', 'Trimethoprim-Sulfamethoxazol']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Aciclovir', array['Acyclovir', 'Zovirax']::text[], 'medication', array['tablet', 'gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Valaciclovir', array['Valacyclovir', 'Valtrex']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fluconazol', array['Fluconazole', 'Diflucan']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Itraconazol', array['Itraconazole', 'Sempera']::text[], 'medication', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Terbinafin', array['Terbinafine', 'Lamisil']::text[], 'medication', array['tablet', 'gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Nystatin', array['Moronal', 'Nystaderm']::text[], 'medication', array['drops', 'tube']::text[], array['IU', 'mg']::text[], null, '{}'::text[]),
    ('Ivermectin', array['Scabioral', 'Soolantra']::text[], 'medication', array['tablet', 'gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Mebendazol', array['Mebendazole', 'Vermox']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Insulin glargin', array['Insulin glargine', 'Lantus', 'Toujeo', 'Abasaglar']::text[], 'hormone', array['pen', 'vial']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Insulin detemir', array['Levemir']::text[], 'hormone', array['pen']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Insulin degludec', array['Tresiba']::text[], 'hormone', array['pen']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Insulin aspart', array['NovoRapid', 'Fiasp']::text[], 'hormone', array['pen', 'vial']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Insulin lispro', array['Humalog', 'Liprolog']::text[], 'hormone', array['pen', 'vial']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Humaninsulin', array['Normalinsulin', 'Insuman', 'Actrapid', 'Huminsulin']::text[], 'hormone', array['pen', 'vial']::text[], array['IU']::text[], null, '{}'::text[]),
    ('Sitagliptin', array['Januvia', 'Xelevia']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Linagliptin', array['Trajenta']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Glimepirid', array['Glimepiride', 'Amaryl']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Gliclazid', array['Gliclazide', 'Diamicron']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Citalopram', array['Cipramil']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fluoxetin', array['Fluoxetine', 'Fluctin', 'Prozac']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Paroxetin', array['Paroxetine', 'Seroxat', 'Tagonis']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Mirtazapin', array['Mirtazapine', 'Remergil']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Duloxetin', array['Duloxetine', 'Cymbalta']::text[], 'medication', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Amitriptylin', array['Amitriptyline', 'Saroten']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Quetiapin', array['Quetiapine', 'Seroquel']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Olanzapin', array['Olanzapine', 'Zyprexa']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Risperidon', array['Risperidone', 'Risperdal']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lamotrigin', array['Lamotrigine', 'Lamictal']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Levetiracetam', array['Keppra']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Valproinsäure', array['Valproic acid', 'Valproat', 'Ergenyl', 'Orfiril']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Pregabalin', array['Lyrica']::text[], 'medication', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Gabapentin', array['Neurontin']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lithium', array['Lithiumcarbonat', 'Quilonum', 'Hypnorex']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Zopiclon', array['Zopiclone', 'Ximovan']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Zolpidem', array['Stilnox', 'Bikalm']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Lorazepam', array['Tavor', 'Ativan']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Diazepam', array['Valium', 'Faustan']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Promethazin', array['Promethazine', 'Atosil']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Metamizol', array['Metamizole', 'Novalgin', 'Novaminsulfon']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Tramadol', array['Tramal', 'Tramundin']::text[], 'medication', array['capsule', 'tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Tilidin', array['Tilidine', 'Valoron']::text[], 'medication', array['capsule', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Oxycodon', array['Oxycodone', 'Oxygesic', 'Targin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Morphin', array['Morphine', 'MST', 'Sevredol']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Hydromorphon', array['Hydromorphone', 'Palladon', 'Jurnista']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Codein', array['Codeine', 'Codipront']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Naproxen', array['Aleve', 'Proxen']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Etoricoxib', array['Arcoxia']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Celecoxib', array['Celebrex']::text[], 'medication', array['capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Sumatriptan', array['Imigran']::text[], 'medication', array['tablet', 'nasal_spray']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Rizatriptan', array['Maxalt']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Esomeprazol', array['Esomeprazole', 'Nexium']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Famotidin', array['Famotidine', 'Pepdul']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Metoclopramid', array['Metoclopramide', 'MCP', 'Paspertin']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Domperidon', array['Domperidone', 'Motilium']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ondansetron', array['Zofran']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Dimenhydrinat', array['Dimenhydrinate', 'Vomex']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Loperamid', array['Loperamide', 'Imodium']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Macrogol', array['Polyethylenglykol', 'Movicol', 'Laxbene']::text[], 'medication', array['powder']::text[], array['g']::text[], null, '{}'::text[]),
    ('Mesalazin', array['Mesalazine', 'Salofalk', 'Pentasa']::text[], 'medication', array['tablet', 'capsule']::text[], array['mg', 'g']::text[], null, '{}'::text[]),
    ('Simeticon', array['Simethicone', 'Lefax', 'Sab simplex']::text[], 'medication', array['tablet', 'capsule', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Formoterol', array['Foradil', 'Oxis']::text[], 'medication', array['spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Salmeterol', array['Serevent']::text[], 'medication', array['spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Tiotropium', array['Spiriva']::text[], 'medication', array['spray', 'capsule']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Ipratropium', array['Atrovent', 'Ipratropiumbromid']::text[], 'medication', array['spray', 'nasal_spray']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Montelukast', array['Singulair']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ambroxol', array['Mucosolvan', 'Ambroxolhydrochlorid']::text[], 'medication', array['tablet', 'drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Desloratadin', array['Desloratadine', 'Aerius']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Levocetirizin', array['Levocetirizine', 'Xusal']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Fexofenadin', array['Fexofenadine', 'Telfast']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Bilastin', array['Bilastine', 'Bilaxten']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Dimetinden', array['Dimetindene', 'Fenistil']::text[], 'medication', array['drops', 'gel', 'tube']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Cromoglicinsäure', array['Cromoglicic acid', 'Cromoglycinsäure', 'DNCG']::text[], 'medication', array['nasal_spray', 'drops']::text[], array['mg', 'mcg']::text[], null, '{}'::text[]),
    ('Dexamethason', array['Dexamethasone', 'Fortecortin']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Methylprednisolon', array['Methylprednisolone', 'Urbason', 'Medrol']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Methotrexat', array['Methotrexate', 'MTX', 'Lantarel', 'Metex']::text[], 'medication', array['tablet', 'pen']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Azathioprin', array['Azathioprine', 'Imurek']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Tamsulosin', array['Alna', 'Omnic']::text[], 'medication', array['capsule', 'tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Solifenacin', array['Vesikur']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Febuxostat', array['Adenuric']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Colchicin', array['Colchicine', 'Colchicum-Dispert']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Alendronsäure', array['Alendronate', 'Alendronat', 'Fosamax']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Risedronsäure', array['Risedronate', 'Risedronat', 'Actonel']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Vardenafil', array['Levitra']::text[], 'medication', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Ethinylestradiol', array['Ethinyl estradiol', 'Ethinylöstradiol']::text[], 'hormone', array['tablet']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Levonorgestrel', array['Pidana', 'Microlut']::text[], 'hormone', array['tablet']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Desogestrel', array['Cerazette', 'Desirett']::text[], 'hormone', array['tablet']::text[], array['mcg']::text[], null, '{}'::text[]),
    ('Drospirenon', array['Drospirenone', 'Slinda']::text[], 'hormone', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Dienogest', array['Visanne']::text[], 'hormone', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Norethisteron', array['Norethisterone', 'Primolut']::text[], 'hormone', array['tablet']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Latanoprost', array['Xalatan']::text[], 'medication', array['drops']::text[], array['mcg', 'mg']::text[], null, '{}'::text[]),
    ('Timolol', array['Timoptol', 'Tim-Ophtal']::text[], 'medication', array['drops']::text[], array['mg']::text[], null, '{}'::text[]),
    ('Brimonidin', array['Brimonidine', 'Alphagan']::text[], 'medication', array['drops']::text[], array['mg']::text[], null, '{}'::text[])
),
aufgeloest as (
  select
    quelle.canonical_name,
    quelle.aliases,
    quelle.default_category,
    quelle.suggested_dosage_forms,
    quelle.suggested_units,
    quelle.component_names,
    -- Das PK-Profil wird ueber Name ODER Alias gesucht, wie schon im
    -- Foundation-Seed: der Katalog schreibt "Semaglutid", das Profil
    -- "Semaglutide".
    (
      select profil.id
      from public.pk_profiles profil
      where quelle.pk_profile_name is not null
        and (
          lower(profil.name) = lower(quelle.pk_profile_name)
          or exists (
            select 1
            from unnest(profil.aliases) profil_alias
            where lower(profil_alias) = lower(quelle.pk_profile_name)
          )
        )
      order by (lower(profil.name) = lower(quelle.pk_profile_name)) desc, profil.id
      limit 1
    ) as pk_profile_id
  from quelle
)
insert into public.substance_catalog as ziel (
  canonical_name,
  aliases,
  default_category,
  suggested_dosage_forms,
  suggested_units,
  pk_profile_id,
  component_names,
  active
)
select
  canonical_name,
  aliases,
  default_category,
  suggested_dosage_forms,
  suggested_units,
  pk_profile_id,
  component_names,
  true
from aufgeloest
on conflict (lower(canonical_name)) do update set
  aliases = excluded.aliases,
  default_category = excluded.default_category,
  suggested_dosage_forms = excluded.suggested_dosage_forms,
  suggested_units = excluded.suggested_units,
  -- Eine bestehende Verknuepfung wird nicht geloescht, nur ergaenzt: steht in
  -- der Quelle kein Profil, bleibt das gefundene stehen.
  pk_profile_id = coalesce(excluded.pk_profile_id, ziel.pk_profile_id),
  component_names = excluded.component_names,
  active = true,
  updated_at = now();

commit;
