// Erzeugt von scripts/generate-effect-duration-sql.mjs — nicht von Hand aendern.
// Alte, uebersetzte Dauer-Texte aller Sprachen → Schluessel (siehe duration.ts).
import type { DurationKey } from './duration'

export const LEGACY_DURATION_TEXTS: Readonly<Record<string, DurationKey>> = {
  "1 Std": 'std_1',
  "1 Tag": 'tag_1',
  "1 Woche": 'woche_1',
  "1 day": 'tag_1',
  "1 dia": 'tag_1',
  "1 día": 'tag_1',
  "1 giorno": 'tag_1',
  "1 gün": 'tag_1',
  "1 h": 'std_1',
  "1 hafta": 'woche_1',
  "1 hari": 'tag_1',
  "1 hr": 'std_1',
  "1 jam": 'std_1',
  "1 jour": 'tag_1',
  "1 minggu": 'woche_1',
  "1 sa": 'std_1',
  "1 semaine": 'woche_1',
  "1 semana": 'woche_1',
  "1 settimana": 'woche_1',
  "1 week": 'woche_1',
  "1 день": 'tag_1',
  "1 неделя": 'woche_1',
  "1 ч": 'std_1',
  "1 س": 'std_1',
  "1 घं": 'std_1',
  "1 दिन": 'tag_1',
  "1 सप्ताह": 'woche_1',
  "12 Std": 'std_12',
  "12 h": 'std_12',
  "12 hrs": 'std_12',
  "12 jam": 'std_12',
  "12 sa": 'std_12',
  "12 ч": 'std_12',
  "12 س": 'std_12',
  "12 घं": 'std_12',
  "12小时": 'std_12',
  "12時間": 'std_12',
  "12시간": 'std_12',
  "15 Min": 'min_15',
  "15 dk": 'min_15',
  "15 min": 'min_15',
  "15 mnt": 'min_15',
  "15 мин": 'min_15',
  "15 دق": 'min_15',
  "15 मिनट": 'min_15',
  "15分": 'min_15',
  "15分钟": 'min_15',
  "15분": 'min_15',
  "1周": 'woche_1',
  "1天": 'tag_1',
  "1小时": 'std_1',
  "1日": 'tag_1',
  "1時間": 'std_1',
  "1週間": 'woche_1',
  "1시간": 'std_1',
  "1일": 'tag_1',
  "1주일": 'woche_1',
  "2 Std": 'std_2',
  "2 Tage": 'tage_2',
  "2 days": 'tage_2',
  "2 dias": 'tage_2',
  "2 días": 'tage_2',
  "2 giorni": 'tage_2',
  "2 gün": 'tage_2',
  "2 h": 'std_2',
  "2 hari": 'tage_2',
  "2 hrs": 'std_2',
  "2 jam": 'std_2',
  "2 jours": 'tage_2',
  "2 sa": 'std_2',
  "2 дня": 'tage_2',
  "2 ч": 'std_2',
  "2 س": 'std_2',
  "2 घं": 'std_2',
  "2 दिन": 'tage_2',
  "2天": 'tage_2',
  "2小时": 'std_2',
  "2日": 'tage_2',
  "2時間": 'std_2',
  "2시간": 'std_2',
  "2일": 'tage_2',
  "30 Min": 'min_30',
  "30 dk": 'min_30',
  "30 min": 'min_30',
  "30 mnt": 'min_30',
  "30 мин": 'min_30',
  "30 دق": 'min_30',
  "30 मिनट": 'min_30',
  "30分": 'min_30',
  "30分钟": 'min_30',
  "30분": 'min_30',
  "4 Std": 'std_4',
  "4 h": 'std_4',
  "4 hrs": 'std_4',
  "4 jam": 'std_4',
  "4 sa": 'std_4',
  "4 ч": 'std_4',
  "4 س": 'std_4',
  "4 घं": 'std_4',
  "4小时": 'std_4',
  "4時間": 'std_4',
  "4시간": 'std_4',
  "8 Std": 'std_8',
  "8 h": 'std_8',
  "8 hrs": 'std_8',
  "8 jam": 'std_8',
  "8 sa": 'std_8',
  "8 ч": 'std_8',
  "8 س": 'std_8',
  "8 घं": 'std_8',
  "8小时": 'std_8',
  "8時間": 'std_8',
  "8시간": 'std_8',
  "Ainda ativo": 'noch_anhaltend',
  "Ancora in corso": 'noch_anhaltend',
  "Aún activo": 'noch_anhaltend',
  "Encore actif": 'noch_anhaltend',
  "Hâlâ devam ediyor": 'noch_anhaltend',
  "Masih berlangsung": 'noch_anhaltend',
  "Noch anhaltend": 'noch_anhaltend',
  "Still ongoing": 'noch_anhaltend',
  "Ещё продолжается": 'noch_anhaltend',
  "أسبوع": 'woche_1',
  "لا يزال مستمراً": 'noch_anhaltend',
  "يوم واحد": 'tag_1',
  "يومان": 'tage_2',
  "अभी जारी है": 'noch_anhaltend',
  "まだ継続中": 'noch_anhaltend',
  "仍在持续": 'noch_anhaltend',
  "아직 진행 중": 'noch_anhaltend',
}
