export type ObAdvance = 'click' | 'next'

export interface OnboardingStepMeta {
  id: string
  emoji: string
  titleKey: string
  subtitleKey: string
  descriptionKey: string
  targetSelector: string | null
  placement: 'auto' | 'top' | 'bottom' | 'center'
  advance: ObAdvance
  /** Navigate when this step becomes active */
  route?: string
  scrollTarget?: boolean
  tapHintKey?: string
  navTarget?: boolean
  /** For center placement: snap card to top or bottom of viewport instead of center */
  snapToViewport?: 'top' | 'bottom'
}

/**
 * Guided tour: inventory (+ Add to stock) → create peptide → cycle → calendar → home features.
 * Step ids match subtitle “Step N” (welcome = intro, no step number in subtitle).
 */
export const ONBOARDING_STEPS: OnboardingStepMeta[] = [
  {
    id: 'welcome',
    emoji: '👋',
    titleKey: 'ob_step_0_title',
    subtitleKey: 'ob_step_0_subtitle',
    descriptionKey: 'ob_step_0_description',
    targetSelector: null,
    placement: 'center',
    advance: 'next',
  },
  {
    id: 'inv-nav',
    emoji: '📦',
    titleKey: 'ob_step_1_title',
    subtitleKey: 'ob_step_1_subtitle',
    descriptionKey: 'ob_step_1_description',
    targetSelector: '[data-ob="nav-lager"]',
    placement: 'top',
    advance: 'click',
    route: '/',
    navTarget: true,
    tapHintKey: 'ob_step_1_tap',
  },
  {
    id: 'add-stock',
    emoji: '➕',
    titleKey: 'ob_step_2_title',
    subtitleKey: 'ob_step_2_subtitle',
    descriptionKey: 'ob_step_2_description',
    targetSelector: '[data-ob="btn-einlagern"]',
    placement: 'bottom',
    advance: 'click',
    tapHintKey: 'ob_step_2_tap',
    route: '/peptide?tab=inventar',
  },
  {
    id: 'inv-name',
    emoji: '🏷️',
    titleKey: 'ob_step_3_title',
    subtitleKey: 'ob_step_3_subtitle',
    descriptionKey: 'ob_step_3_description',
    targetSelector: '[data-ob="inv-name"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'inv-amounts',
    emoji: '💊',
    titleKey: 'ob_step_4_title',
    subtitleKey: 'ob_step_4_subtitle',
    descriptionKey: 'ob_step_4_description',
    targetSelector: '[data-ob="inv-amounts"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'inv-batch',
    emoji: '📋',
    titleKey: 'ob_step_5_title',
    subtitleKey: 'ob_step_5_subtitle',
    descriptionKey: 'ob_step_5_description',
    targetSelector: '[data-ob="inv-batch"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'inv-save',
    emoji: '💾',
    titleKey: 'ob_step_6_title',
    subtitleKey: 'ob_step_6_subtitle',
    descriptionKey: 'ob_step_6_description',
    targetSelector: '[data-ob="btn-inv-save"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_6_tap',
    scrollTarget: true,
  },
  {
    id: 'create-peptide',
    emoji: '🧪',
    titleKey: 'ob_step_7_title',
    subtitleKey: 'ob_step_7_subtitle',
    descriptionKey: 'ob_step_7_description',
    targetSelector: '[data-ob="btn-peptid-anlegen"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_7_tap',
    scrollTarget: true,
  },
  {
    id: 'pep-liquid',
    emoji: '💧',
    titleKey: 'ob_step_8_title',
    subtitleKey: 'ob_step_8_subtitle',
    descriptionKey: 'ob_step_8_description',
    targetSelector: '[data-ob="pep-liquid"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'pep-expiry',
    emoji: '📅',
    titleKey: 'ob_step_9_title',
    subtitleKey: 'ob_step_9_subtitle',
    descriptionKey: 'ob_step_9_description',
    targetSelector: '[data-ob="pep-expiry"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'pep-dose',
    emoji: '💉',
    titleKey: 'ob_step_10_title',
    subtitleKey: 'ob_step_10_subtitle',
    descriptionKey: 'ob_step_10_description',
    targetSelector: '[data-ob="pep-dose"]',
    placement: 'top',
    advance: 'next',
    scrollTarget: true,
  },
  {
    id: 'pep-save',
    emoji: '✅',
    titleKey: 'ob_step_11_title',
    subtitleKey: 'ob_step_11_subtitle',
    descriptionKey: 'ob_step_11_description',
    targetSelector: '[data-ob="btn-pep-save"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_11_tap',
    scrollTarget: true,
  },
  {
    id: 'pep-tab',
    emoji: '🔬',
    titleKey: 'ob_step_12_title',
    subtitleKey: 'ob_step_12_subtitle',
    descriptionKey: 'ob_step_12_description',
    targetSelector: '[data-ob="tab-peptide"]',
    placement: 'bottom',
    advance: 'click',
    tapHintKey: 'ob_step_12_tap',
    route: '/peptide',
  },
  {
    id: 'add-cycle',
    emoji: '🔄',
    titleKey: 'ob_step_13_title',
    subtitleKey: 'ob_step_13_subtitle',
    descriptionKey: 'ob_step_13_description',
    targetSelector: '[data-ob="btn-zyklus-add"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_13_tap',
    scrollTarget: true,
  },
  {
    id: 'cycle-plan',
    emoji: '📋',
    titleKey: 'ob_step_14_title',
    subtitleKey: 'ob_step_14_subtitle',
    descriptionKey: 'ob_step_14_description',
    targetSelector: null,
    placement: 'center',
    advance: 'next',
    snapToViewport: 'top',
  },
  {
    id: 'cycle-save',
    emoji: '💾',
    titleKey: 'ob_step_15_title',
    subtitleKey: 'ob_step_15_subtitle',
    descriptionKey: 'ob_step_15_description',
    targetSelector: '[data-ob="btn-cycle-save"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_15_tap',
    scrollTarget: true,
  },
  {
    id: 'calendar-nav',
    emoji: '🗓️',
    titleKey: 'ob_step_16_title',
    subtitleKey: 'ob_step_16_subtitle',
    descriptionKey: 'ob_step_16_description',
    targetSelector: '[data-ob="nav-kalender"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_16_tap',
    navTarget: true,
    route: '/kalender',
  },
  {
    id: 'calendar-use',
    emoji: '📆',
    titleKey: 'ob_step_17_title',
    subtitleKey: 'ob_step_17_subtitle',
    descriptionKey: 'ob_step_17_description',
    targetSelector: '[data-ob="calendar-main"]',
    placement: 'bottom',
    advance: 'next',
    route: '/kalender',
  },
  {
    id: 'home-nav',
    emoji: '🏠',
    titleKey: 'ob_step_18_title',
    subtitleKey: 'ob_step_18_subtitle',
    descriptionKey: 'ob_step_18_description',
    targetSelector: '[data-ob="nav-home"]',
    placement: 'top',
    advance: 'click',
    tapHintKey: 'ob_step_18_tap',
    navTarget: true,
    route: '/',
  },
  {
    id: 'home-features',
    emoji: '✨',
    titleKey: 'ob_step_19_title',
    subtitleKey: 'ob_step_19_subtitle',
    descriptionKey: 'ob_step_19_description',
    targetSelector: '[data-ob="home-tiles"]',
    placement: 'bottom',
    advance: 'next',
    route: '/',
  },
  {
    id: 'finish',
    emoji: '🚀',
    titleKey: 'ob_step_20_title',
    subtitleKey: 'ob_step_20_subtitle',
    descriptionKey: 'ob_step_20_description',
    targetSelector: null,
    placement: 'center',
    advance: 'next',
  },
]

export const ONBOARDING_STEP_COUNT = ONBOARDING_STEPS.length

/** Steps that count as “Step 1…N” in the UI (excludes welcome + finish) */
export const ONBOARDING_TOUR_STEP_COUNT = ONBOARDING_STEP_COUNT - 2
